### ISSUE TITLE
Windows Read Error

### ISSUE THREAD

**Issue by HsunGong** [nttcslab-sp/kaldiio#35]
I'd like to read a 'scp' or `ark` file under windows-python, but it returns like below

```
C:\Users\xun\AppData\Roaming\Python\Python37\site-packages\kaldiio\utils.py:328: UserWarning: An error happens at loading "data/align.ark:589971"
  'An error happens at loading "{}"'.format(ark_name))
Traceback (most recent call last):
  File "C:\Users\xun\AppData\Roaming\Python\Python37\site-packages\kaldiio\utils.py", line 325, in __getitem__
    return self._loader(ark_name)
  File "C:\Users\xun\AppData\Roaming\Python\Python37\site-packages\kaldiio\matio.py", line 204, in load_mat
    return _load_mat(fd, offset, slices, endian=endian, as_bytes=as_bytes)
    array = read_kaldi(fd, endian)
  File "C:\Users\xun\AppData\Roaming\Python\Python37\site-packages\kaldiio\matio.py", line 343, in read_kaldi
    array, size = read_ascii_mat(fd, return_size=True)
  File "C:\Users\xun\AppData\Roaming\Python\Python37\site-packages\kaldiio\matio.py", line 536, in read_ascii_mat
    array = np.loadtxt(StringIO(string), dtype=dtype, ndmin=ndmin)
  File "C:\Users\xun\AppData\Roaming\Python\Python37\site-packages\numpy\lib\npyio.py", line 1141, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "C:\Users\xun\AppData\Roaming\Python\Python37\site-packages\numpy\lib\npyio.py", line 1065, in read_data
    % line_num)
ValueError: Wrong number of columns at line 2
```

It seems like while `read_ascii_mat`, we got error strings. I print it out and find it contains 2 lines:
the first line is the feat above, the second string is what we want
```
117 117 117 117 117 117 117 117 69 69 69 69 81 81 81 81 81 107 107 107 107 107 107 65 65 65 65 65 65 65 65 65 65 65 65 38 38 38 38 38 38 38 38 38 16 16 16 16 16 16 16 16 44 44 44 44 44 44 44 44 65 65 65 65 65 65 65 65 65 65 65 34 34 34 34 34 34 34 34 34 34 34 34 34 94 94 94 94 94 94 94 94 94 94 94 94 94 94 
94 94 119 119 119 119 119 119 119 39 39 39 39 39 39 39 39 39 19 19 19 19 19 19 19 43 43 43 43 65 65 65 65 65 65 65 65 65 30 30 30 30 30 30 30 30 30 30 30 
30 30 30 30 30 30 30 16 16 16 16 16 16 16 16 16 16 16 87 87 87 87 87 118 118 118 118 118 118 118 118 37 37 37 37 37 37 66 66 66 66 66 66 66 66 66 66 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
ast100 83 83 83 83 83 83 83 83 83 83 83 83 83 85 85 85 85 85 85 85 85 85 85 85 85 85 85 85 85 85 85 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 117 117 117 117 117 117 117 117 117 117 69 69 69 69 69 69 61 61 61 61 61 61 61 61 61 61 61 61 61 61 46 46 46 46 46 46 46 46 46 65 65 65 65 65 65 65 65 38 38 38 38 38 38 19 19 19 19 19 19 24 24 24 24 24 24 24 78 78 78 78 78 78 78 78 78 78 78 78 78 36 36 36 36 36 36 36 36 36 36 36 36 81 81 81 37 37 37 37 37 37 32 32 32 32 32 32 32 32 32 32 32 32 32 32 16 16 16 16 
16 16 16 44 44 44 44 44 44 44 44 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 65 120 120 120 120 120 120 120 22 22 22 22 22 65 65 65 65 64 64 64 64 64 24 24 24 24 24 24 24 24 119 119 119 119 119 119 119 4 4 4 4 4 4 4 4 66 66 66 63 63 63 63 63 63 63 63 24 24 24 24 24 24 24 24 24 24 24 24 24 24
```

**Comment by nttcslab-sp-admin** [comment]
Thanks! We haven't tested it on Windows. Now the problem was fixed. Please update kaldiio.
