### ISSUE TITLE
ValueError: Unexpected format <Nnet3Eg>

### ISSUE THREAD

**Issue by FredMushZhao** [nttcslab-sp/kaldiio#54]
it's a good package that helps me a lot, but when I use it to load scp files (exp/xvector_nnet/egs/egs.1.scp for example) that kaldi prepared in egs/sre16 scripts,  an ValueError occured, here's the traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/torch/lib/python3.8/site-packages/kaldiio-2.17.0-py3.8.egg/kaldiio/matio.py", line 339, in load_ark
  File "/home/torch/lib/python3.8/site-packages/kaldiio-2.17.0-py3.8.egg/kaldiio/matio.py", line 429, in read_kaldi
  File "/home/torch/lib/python3.8/site-packages/kaldiio-2.17.0-py3.8.egg/kaldiio/matio.py", line 518, in read_matrix_or_vector
ValueError: Unexpected format: "<Nnet3Eg>". Now FM, FV, DM, DV, CM, CM2, CM3 are supported.
 I suspect that <Nnet3Eg> is just an alias for the supported format, but have no idea how to do solve it. Is there any solutions? Thanks a lot.

**Comment by kamo-naoyuki** [comment]
egs format is not supported.

**Comment by FredMushZhao** [comment]
well, thanks again. i just found it in Readme, sorry for disturbing you.

**Comment by kamo-naoyuki** [comment]
https://github.com/funcwj/kaldi-python-io

This tool supports egs format.
