### ISSUE TITLE
UnicodeDecodeError when load cmvn.ark

### ISSUE THREAD

**Issue by cantabile-kwok** [nttcslab-sp/kaldiio#57]
Thanks for your tool which spares me really a lot of time working with kaldi files.

Recently I met a problem which I cannot solve. I firstly use the kaldi command `apply-cmvn` to compute the statistics of my dataset, and that generates `cmvn.ark`. I want to see the values in this file, but when I use 
```
data = kaldiio.load_ark('cmvn.ark')
for k, v in data:
    # do something
```
I met this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/matio.py", line 348, in load_ark
    array = read_kaldi(fd, endian)
  File "/opt/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/matio.py", line 441, in read_kaldi
    array = read_ascii_mat(fd)
  File "/opt/anaconda3/envs/espnet/lib/python3.8/site-packages/kaldiio/matio.py", line 588, in read_ascii_mat
    char = fd.read(1).decode(encoding=default_encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 0: unexpected end of data
```
However, this problem doesn't exist when loading `feats.ark` or other files. It seems it's only `cmvn.ark` that has this problem. I thought this file was broken, but I succeeded in using it by further kaldi commands such as `dump.sh` to obtain the normalized features. 

Does this file have other formats than `feats.ark`? Do I have to pass extra arguments to `load_ark`? I am no expert in kaldi, so I'd be grateful if you have any hints.

**Comment by cantabile-kwok** [comment]
I came across this issue again recently, and I found `load_mat` might be the correct one for that 😄
